### ISSUE TITLE
Expand the "Restore" section with Borgmatic

### ISSUE THREAD

**Issue by meowmix3** [borgbase/docs.borgbase.com#2]
Hello!  I believe it would be beneficial to expand the Restore section with steps to restoring your backups with Borgmatic, as I find it to be a bit easier to use and friendlier than the plain borg syntax--and the other sections as well as the main website go into detail on configuring it.

Here is a short sample write-up:

## Step 5 - Restoring with Borgmatic (optional)
If you use Borgmatic for your regular backups, it may be easier to use the Borgmatic syntax, provided you have a correctly configured configuration file.

Assuming that you have Borgmatic correctly configured and making backups, you would first need to find the backup you need to restore by listing the archives.
```
$ borgmatic -l
```

After choosing the backup, you would then add it to the `borgmatic -x` command
```
$ borgmatic -x server-2020-04-01T12:11:41
```

Make sure you are in the directory you would like to restore to, as it will extract the files into it.

If you would only like restore a particular directory from a backup, its as easy as adding `--restore path` to the command, along with the directory or file you would like to restore (minus the first `/`).

For example, if you would like to only restore `/mnt/catpics` from the same archive, the full command would be:
```
$ borgmatic -x server-2020-04-01T12:11:41 --restore-path 'mnt/catpics'
```

**Comment by m3nu** [comment]
Good stuff. All for giving multiple options to restore files.

How about splitting the Restore article into 4 pages:

- `/restore`: Overview article with some general tips (like a warning that the repo password is required) and the available options (=subpages listed below)
- `/restore/mount`: How to restore using `borg mount` and FUSE
- `/restore/extract`: Restore by using `borg extract`
- `/restore/borgmatic`: Restore using Borgmatic as described above.

I would find this easier to understand because we don't really have different steps here, but different options that can stand on their own.

What do you think, @meowmix3 ?

**Comment by m3nu** [comment]
The overview article at `/restore` could also link to Vorta's restore docs (currently empty)

https://vorta.borgbase.com/usage/restore/

**Comment by meowmix3** [comment]
That sounds great, I can write the additional articles and create a pull request sometime this week if you would like.

**Comment by m3nu** [comment]
Yes please. Looking forward to it.

**Comment by skerit** [comment]
Borgmatic complains this command misses the `-archive` option?

**Comment by m3nu** [comment]
Yeah, time to add this. I'll make sure Borgmatic args are up-to-date. Maybe they changed since then.

**Comment by m3nu** [comment]
I've updated the Bormatic page. Please let me know if I missed anything.

https://docs.borgbase.com/restore/borgmatic/
